### PR TITLE
#248

### PR DESCRIPTION
**Pull request by daviddq**

### CODE REVIEW

**Comment by blurymind** [comment]
This appears to cause a regression, instead of renaming the link it creates a new one
regressionRenameLinks

**Comment by blurymind** [comment]
Thank you for working on this! Merged now :tada:

**Comment by daviddq** [comment]
It works the other way around: renaming the node updates the links. You
probably saw it already since you merged the change.

**Comment by blurymind** [comment]
Yeah I did. Sorry I totally forgot that detail. :)

**Pull request merged**
