### PR TITLE
Auto release

### PR DESCRIPTION
**Pull request by daviddq**
This PR implements auto release.

To achieve an auto release:

1) Switch to _master_ branch
2) Decide which commit will be released
3) Find out the version in package.json
4) Tag the commit with the pattern `vM.m.p` (M=Major, m=minor, p=patch, i.e. v0.4.10). Notice that the tag must start with 'v'. Major, minor and patch must match those in package.json

### CODE REVIEW

**Comment by blurymind** [comment]
Thank you for working on this! :+1: 
I will merge it and give it a try

**Comment by blurymind** [comment]
merged :tada:

**Comment by blurymind** [comment]
We have a github action that does an automatic commit for us
"GitHub Action Update version"

Can we make the action include in the commit the pattern required to trigger an electron build+release?

**Comment by daviddq** [comment]
"GitHub Action Update version" is in charge of incrementing the version number on each new build of _master_. That's completely decoupled from release.

Ideally the release process should imply:

- Picking a commit with the desired/planned features to be released.
- Performing a QA cycle to ensure everything works fine.
- Only when the quality of the commit is assured, tag that commit with the corresponding version number.
- After tagging, the "build and release" process will be automatically triggered.

Generally speaking is not a good idea to automatically and blindly release everything that's buit.

**Comment by blurymind** [comment]
I do QA on each PR

@desplesda can you try doing an automatic electron release following the instructions @daviddq outlines here? I have no idea how to tag commits :shrug:

**Comment by daviddq** [comment]
1) pick a commit of your choice (e8996f4 is the latest one)
2) get the version from the package.json of that commit (0.4.14)
3) tag the commit with the corresponding version:

`$ git tag -a v0.4.14 e8996f4`

**Comment by blurymind** [comment]
I usually do this stuff with gitkraken. How does one apply the tag? The keyboard shortcut? The command gets me stuck in something that looks like vim

**Comment by daviddq** [comment]
I use CLI, VSCode Git extension or SourceTree. I know little to nothing about GitKraken but it looks easy at first sight: https://support.gitkraken.com/working-with-repositories/tags/

**Comment by blurymind** [comment]
> 5\. v0.4.14

I gave it a try, lets see now :)

**Comment by daviddq** [comment]
So far so good 😉 

image

**Pull request merged**
