### PR TITLE
Fixes issue #127 Navigating back to previously edited nodes when the nodes have been renamed results in new nodes being created

### PR DESCRIPTION
**Pull request by daviddq**
Fixes issue #127 Navigating back to previously edited nodes when the nodes have been renamed results in new nodes being created

### CODE REVIEW

**Comment by blurymind** [comment]
It has some merge conflicts. Can you resolve them please :) 

You have to merge master into your branch, resolve the conflicts and then push the commit that resolves them

**Comment by blurymind** [comment]
sorry about this btw, it must have happened because I recently did some fixes on the same file

**Comment by daviddq** [comment]
No worries.

Conflicts solved.

**Comment by blurymind** [comment]
I'm not entirely sure why, but your whole app.js file is appearing in the diff, so it is kind of impossible for me to review this properly :)

**Comment by daviddq** [comment]
Same thing happened to me with your change, probably due to different prettiers or versions. Let me see...

**Comment by daviddq** [comment]
I'm going to branch again from _master_ and submit a new PR since I'm not able to re-commit app.js with only my changes.

**Pull request closed without merging**
