### PR TITLE
Continuous integration on GitHub

### PR DESCRIPTION
**Pull request by daviddq**
For this to work you need go to **Settings\Developer Settings\Personal access tokens** 

image

image

image

and generate a token with the following scopes:

image

Then go to **repository settings\secrets** and add a new secret with name GH_TOKEN and value the token that you created on the steps above:

image

image

### CODE REVIEW

**Comment by blurymind** [comment]
@desplesda is the man for this one :)

**Comment by desplesda** [comment]
Nice!! Will set this up.

This CI is only for Linux - how easy would it be to generate the Windows and macOS builds too?

**Comment by daviddq** [comment]
I tested Linux first since it was the easiest and I was unsure if you were interested in this.

Mac should be straightforward, probably there's only the need to change the build running platform.

For my local Windows build there's a dependency ("node-sass": "^4.12.0",) that has no binary available, so npm downloads the sources and uses gyp to build the binary. Unfortunately this needs Windows SDK installed. If I could update that dependency to "node-sass": "^4.13.1" the build step would be unnecessary, I guess.

**Comment by blurymind** [comment]
I can look into removing that dependency if its preventing windows builds

**Comment by daviddq** [comment]
I noticed that just upgrading it to version 4.13.1 solves the problem. For version 4.12.0 it gives a 404 error. I didn't dig much on this issue. Let me try this afternoon.

**Comment by daviddq** [comment]
But, of course, if the dependency is not needed, please, remove it.

**Comment by daviddq** [comment]
All three builds are available now:

image

**Comment by blurymind** [comment]
Well done :)

**Comment by blurymind** [comment]
It's up to @desplesda now todo the rest. He has the keys to this repository :smiley_cat:

**Comment by desplesda** [comment]
👍! Will update you when it’s ready.

**Comment by daviddq** [comment]
Any news on this? I see there's a conflict, probably for wanting to add the build configuration to `.github/workflows`.  Do you need any help with this?

**Comment by desplesda** [comment]
Hi! I’m free tomorrow to do a bunch of admin tasks on this. Apologies for the lack of movement so far, but it hasn’t fallen off my radar.

**Comment by desplesda** [comment]
Ok, the secret `GH_TOKEN` has been set up with a PAT, which has the permissions that @daviddq  listed.

**Comment by daviddq** [comment]
Cool!

What about the merge conflict? It seems I'm not allowed to write to .github/workflows/nodejs.yml for security reasons I guess.

image

**Comment by desplesda** [comment]
Done!

**Comment by desplesda** [comment]
Looks like Windows and Linux are working fine! 

It looks like the macOS CI is failing due to a lack of a code signing identity. Let me know what you need from me so that we can continue signing it with the current credentials (i.e. my developer certificate)!

**Comment by daviddq** [comment]
image

**Comment by desplesda** [comment]
Oh, strange. The build https://github.com/YarnSpinnerTool/YarnEditor/actions/runs/75909919 failed, but on closer inspection it didn't fail because of code signing, but rather because it failed to run `hdiutil`. Not 100% sure why.

**Comment by daviddq** [comment]
Exactly! This is the error:

image

Code signing is optional. I had some random errors on my fork. Let's see how it breathes in the next builds.

**Comment by daviddq** [comment]
Latest Win/Mac builds failed with:

`⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
`
But Linux one worked ¿¿¿???

**Comment by daviddq** [comment]
The GH_TOKEN seems to be available for _master_ builds but not for PR builds:

Captura de pantalla 2020-04-21 a las 12 37 47

Maybe there's the need to provide permissions to use GH_TOKEN on other forks/branches/whatever, @desplesda ?

**Pull request merged**
