### PR TITLE
Fixed a bug refreshing incoming links from other nodes

### PR DESCRIPTION
**Pull request by daviddq**

### CODE REVIEW

**Comment by daviddq** [comment]
This bug goes unnoticed if "auto create new nodes" is ON. Now that on my fork I can set it OFF from the Settings Dialog it showed up.

**Comment by daviddq** [comment]
Any news on this?

**Comment by blurymind** [comment]
Code looks good, just needs testing. Will try to merge it tomorrow

**Comment by blurymind** [comment]
Nice catch :+1: 
merged to master :tada:

**Pull request merged**
